
services:
  kafka:
    image: apache/kafka:4.1.2
    hostname: kafka
    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"

      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

    volumes:
      - kafka_data:/var/lib/kafka/data

    healthcheck:
      test:
        - CMD
        - /opt/kafka/bin/kafka-topics.sh
        - --bootstrap-server
        - localhost:9092
        - --list
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8080:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: "WeatherStream Local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"

    depends_on:
      kafka:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: weatherstream-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: weatherstream
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in your .env file}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weather_user -d weatherstream"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  kafka_data:
  postgres_data:
